name: flutter_habit_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  isar:
    hosted: https://pub.isar-community.dev
    version: 3.1.7
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: 3.1.7
  path_provider: ^2.1.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: 3.1.7
  build_runner: any


flutter:
  uses-material-design: true
